//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public string experience { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string designation { get; set; }
        public string skillSet { get; set; }
    }
}
